Homework1
AlexandraLindau/playwright pull request #1
Opened 2023-11-22 20:58 UTC by AlexandraLindau

2023-11-24 17:05 UTC, ovartem requested changes

2023-11-24 17:05 UTC, ovartem commented on .github/workflows/playwright.yml
> +name: Playwright Tests
Add test launch by cron - nightly

2023-11-24 17:05 UTC, ovartem commented on package.json
> +  "scripts": {},
add scripts to 
1. launch tests, 
2. open playwright ui

2023-11-24 17:05 UTC, ovartem commented on package.json
> +  "scripts": {},
change github actions

2023-11-24 17:05 UTC, ovartem commented on playwright.config.js
> + * https://github.com/motdotla/dotenv
add baseUrl to config https://playwright.dev/docs/test-configuration

2023-11-24 17:05 UTC, ovartem commented on PageObjects/CartPage.js
> +        this.products = '.cart_item';
```suggestion
        this.products = this.page.locator('.cart_item');
```

2023-11-24 17:05 UTC, ovartem commented on PageObjects/CartPage.js
> +
getItemDescription(ind) {
  return `...${ind}`;
}

2023-11-24 17:05 UTC, ovartem commented on PageObjects/CartPage.js
> +        return new Product(title, description, price);
```suggestion
        return { title, description, price };
```

2023-11-24 17:05 UTC, ovartem commented on PageObjects/CartPage.js
> +    async getProductByIndex(index) {
```suggestion
    async getProductByIndex(index: number): Promise<IProduct> {
```
The above comment is related to TS migration

2023-11-24 17:05 UTC, ovartem commented on PageObjects/CartPage.js
> +        const removeButtonLocator = this.product.button.replace('{INDEX}', index);
Alligne with the changes suggested in above comments

2023-11-24 17:05 UTC, ovartem commented on PageObjects/Components/HeaderComponent.js
> +    async getTitle() {
use getters instead of methods

2023-11-24 17:05 UTC, ovartem commented on models/Product.js
> +class Product {
No need to use it

2023-11-24 17:05 UTC, ovartem commented on PageObjects/ProductsPage.js
> +        this.product = {
Add Abstract class

2023-11-24 17:05 UTC, ovartem commented on tests/data-provider.js
> +    username: 'standard_user',
Add .env file support
You can use dotenv npm package to use .env file or use node version 20 or higher for that

2023-11-24 17:05 UTC, ovartem commented on tests/data-provider.js
> +    username: 'standard_user',
add .env file to gitignore

2023-11-24 17:05 UTC, ovartem commented on .github/workflows/playwright.yml
> +name: Playwright Tests
Once you use .env file this yaml needs to be updated to use github secrets

2023-11-28 00:13 UTC, AlexandraLindau commented on .github/workflows/playwright.yml
> +name: Playwright Tests
Done

2023-11-28 00:30 UTC, AlexandraLindau commented on package.json
> +  "scripts": {},
Done

2023-11-28 00:30 UTC, AlexandraLindau commented on playwright.config.js
> + * https://github.com/motdotla/dotenv
Done

2023-11-28 00:30 UTC, AlexandraLindau commented on PageObjects/CartPage.js
> +        this.products = '.cart_item';
Fixed

2023-11-28 00:31 UTC, alindau commented on PageObjects/CartPage.js
> +
Done

2023-11-28 00:31 UTC, AlexandraLindau commented on PageObjects/CartPage.js
> +        return new Product(title, description, price);
Fixed

2023-11-28 00:31 UTC, AlexandraLindau commented on PageObjects/CartPage.js
> +    async getProductByIndex(index) {
Done

2023-11-28 00:31 UTC, AlexandraLindau commented on PageObjects/CartPage.js
> +        const removeButtonLocator = this.product.button.replace('{INDEX}', index);
Done

2023-11-29 19:54 UTC, ovartem requested changes
Great Job! Really good. I've left several small comments

2023-11-29 19:54 UTC, ovartem commented on PageObjects/CartPage.ts
> +    product: { title: string; quantity: string; description: string; price: string; button: string; };
`{ title: string; quantity: string; description: string; price: string; button: string; }` this can be moved somewhere and used as an interface

2023-11-29 19:54 UTC, ovartem commented on PageObjects/Components/HeaderComponent.ts
> +        this.title = this.page.locator('.title').first();
I think the header should have some base component or some div which can be used to locate elements inside and avoid using .first() method.

2023-11-29 19:54 UTC, ovartem commented on PageObjects/LoginPage.ts
> +    async logIn(username, password) {
```suggestion
    async logIn(username: string, password: string) {
```

2023-11-29 19:54 UTC, ovartem commented on package.json
> +    "dotenv": "^16.3.1"
These dependencies should be changed vise versa

2023-11-30 19:27 UTC, merged